management:
    security:
        enabled: false
server:
  port: 7172
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://127.0.0.1:8761/eureka/
